### ISSUE TITLE
Question about weight initialisation

### ISSUE THREAD

**Issue by gaomingqi** [seoungwugoh/STM#10]
Hi, thanks for sharing your great work!

I am trying to reproduce the training code and I have 2 questions about how to initialise the weights in STM model: 
**1.** In your released code, the backbone network (ResNet-50) uses the weights pre-trained on ImageNet to extract features from video sequence, so does that mean this network module is not fine-tuned further during training? 
**2.** How to initialise the weights in the _Decoder module_ and _the convolutional layers for computing key and value features_? With the ones generated randomly or pre-trained on some segmentation datasets?

Thank you so much for your consideration and look forward to hearing from you soon!

**Comment by seoungwugoh** [comment]
@gaomingqi Hi, here is my answers: 1) it was just for initialization, it is fine-tuned during training. 2) Initialization for weights except for ResNet is done randomly (through Kaiming He initialization). Note that we have two training stages: pre-training on images and main training on videos. There is no pre-pre training.

**Comment by gaomingqi** [comment]
Thank you so much for your reply!
