### ISSUE TITLE
Confusion about the memory encoder implementation

### ISSUE THREAD

**Issue by xmlyqing00** [seoungwugoh/STM#11]
Hi,

Thanks for your outstanding model and well implementation. I have a question about memory encoder.
In the class `Encoder_M`, you sum up the frame and the mask at the very beginning:
```
x = self.conv1(f) + self.conv1_m(m) + self.conv1_o(o) 
```
However, it is confusing that in your paper, you say 
> The inputs are concatenated along the channel dimension before being fed into the memory encoder. 
> For the memory encoder, the first convolution layer is modified to be able to take a 4-channel tensor by implanting additional single channel filters.
 
Could you explain this difference or talk more about the intuition behind your implementation? 
Thanks in advance.

**Comment by xmlyqing00** [comment]
Thanks for the author's reply. They are equivalent.

**Comment by pixelsmaker** [comment]
> Thanks for the author's reply. They are equivalent.

why are they equivalent?

**Comment by seoungwugoh** [comment]
@pixelsmaker 
It is because convolution is a linear operation.  Thus, applying a single convolution after concatenating all the inputs are exactly equivalent to summing outputs from separate convolution applied to each input.
