### ISSUE TITLE
PIL.putpalette

### ISSUE THREAD

**Issue by MasterBin-IIAU** [seoungwugoh/STM#12]
Hi, when I run STM on DAVIS16, I came across the following problem.
Traceback (most recent call last):
  File "/home/masterbin-iiau/Desktop/STM/eval_DAVIS.py", line 131, in <module>
    img_E.putpalette(palette)
  File "/home/masterbin-iiau/anaconda3/envs/VOT20/lib/python3.6/site-packages/PIL/Image.py", line 1641, in putpalette
    data = bytes(data)
TypeError: cannot convert 'NoneType' object to bytes

palette = Image.open(DATA_ROOT + '/Annotations/480p/blackswan/00000.png').getpalette()
the path is right but getpalette() return None.

Is this problem related to the version of pillow? I am using pillow=6.1.0
Could you give me some advice? Thank you

**Comment by MasterBin-IIAU** [comment]
Sorry, it's my problem. I downloaded the wrong datasets. 
When I prepare DAVIS correctly, the problem is gone.

**Comment by darkliang** [comment]
> Sorry, it's my problem. I downloaded the wrong datasets.
> When I prepare DAVIS correctly, the problem is gone.

I also met this problem, could you tell me how you solved it?

**Comment by MasterBin-IIAU** [comment]
@darkliang 
Hi, Please download DAVIS 16 from this link ([DAVIS16](https://davischallenge.org/davis2016/code.html)). I think if the dataset is right, this problem should not appear.

**Comment by darkliang** [comment]
@MasterBin-IIAU Thank you for your help. I did download the dataset from this link, but the problem still arises. And if I use DAVIS2017, the palette is available.

**Comment by darkliang** [comment]
@MasterBin-IIAU Thanks again, I figure out this problem, the correct dataset that contains color annotations is in [DAVIS2017](https://data.vision.ee.ethz.ch/csergi/share/davis/DAVIS-2017-trainval-480p.zip).

**Comment by BigBoomDream** [comment]
@darkliang Thank you for your help.
