### ISSUE TITLE
how did you sample 3 temporally ordered frames of main training? 

### ISSUE THREAD

**Issue by aaaaannnnn11111** [seoungwugoh/STM#2]
Hi,According to your paper that you sampled 3 temporally ordered frames in main training and the
maximum number of frames to be skipped is gradually increased from 0 to 25 ,but you have sampled 3 frames,so is the gap between each TWO frame increased from 0 to 25?

**Comment by seoungwugoh** [comment]
Yes, we control the difficulty of the training using frame skipping. 
Skipping distance between each two frames are randomly sampled in [0, maximum_skip],
where maximum_skip increased from 0 to 25 during training.
