### ISSUE TITLE
The output pred is all 0

### ISSUE THREAD

**Issue by guguflyy** [seoungwugoh/STM#40]
Thanks for the good work done.I tried to repeat your results.
But the final output img image is all black, check and find that the pred output of Run_video() is all 0. Why does this happen? Is it a problem with the test data format I'm using? Or is it some other reason?
Waiting for your reply!

**Comment by ElleDrake** [comment]
hi, I got the same question, do you have solved it now? thanks.

**Comment by JingWwwwwj** [comment]
I got the same question too, do you guys have solved this problem? thanks !

**Comment by zivvvvvwang** [comment]
I have the same problem. Has anyone solved this problem?
